# Generated by Django 5.0 on 2023-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('problem', models.TextField()),
                ('date', models.DateField()),
                ('selected', models.CharField(max_length=50, null=True)),  # Add the selected field here
            ],
        ),
        migrations.CreateModel(
            name='savedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
