# Generated by Django 5.0 on 2023-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='selected',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
