# Generated by Django 5.0 on 2023-12-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_savedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
