# Generated by Django 5.0 on 2023-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_savedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('workarea', models.CharField(choices=[('PL', 'Plumbing'), ('EL', 'Electrical'), ('O', 'Other')], default='', max_length=30)),
                ('citizenship_image', models.ImageField(default='', upload_to='media/')),
                ('certificate_image', models.ImageField(default='', upload_to='media/')),
            ],
        ),
    ]
