# Generated by Django 5.0 on 2023-12-18 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_workerstat_workarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstat',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
