# Generated by Django 5.0 on 2023-12-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_workerstat_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerstat',
            name='user_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
