# Generated by Django 5.0 on 2023-12-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_date_request_request_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_date',
            new_name='date',
        ),
    ]
