# Generated by Django 5.0 on 2023-12-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_workerstat_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerstat',
            name='user_name',
        ),
    ]
