# Generated by Django 5.0 on 2023-12-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_workerstat_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerstat',
            name='id',
        ),
        migrations.AlterField(
            model_name='workerstat',
            name='worker_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
