# Generated by Django 5.0 on 2023-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_workerstat_id_alter_workerstat_worker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_name', models.CharField(default='', max_length=40)),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='workerstat',
            name='user_name',
        ),
        migrations.AddField(
            model_name='workerstat',
            name='worker_user_name',
            field=models.CharField(default='', max_length=40, unique='True'),
        ),
        migrations.AlterField(
            model_name='workerstat',
            name='certificate_image',
            field=models.ImageField(default='', upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='workerstat',
            name='citizenship_image',
            field=models.ImageField(default='', upload_to='static/media/'),
        ),
    ]
