# Generated by Django 5.0 on 2023-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userdata_remove_workerstat_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_image',
            field=models.ImageField(default='', upload_to='static/media/userimage'),
        ),
        migrations.AlterField(
            model_name='workerstat',
            name='certificate_image',
            field=models.ImageField(default='', upload_to='static/media/certificate'),
        ),
        migrations.AlterField(
            model_name='workerstat',
            name='citizenship_image',
            field=models.ImageField(default='', upload_to='static/media/citizen'),
        ),
    ]
