# Generated by Django 5.0 on 2023-12-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userdata_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
